# Generated by Django 3.0.5 on 2020-11-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfiles',
            name='file_input',
            field=models.FileField(upload_to=''),
        ),
    ]
